const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
function phone(v){let d=String(v||"").replace(/\D/g,"");if(d.length===11&&d[0]==="8")d="7"+d.slice(1);if(d.length===10)d="7"+d;return /^7\d{10}$/.test(d)?"+"+d:null}
async function validInitData(raw,token){if(!raw||!token)return null;const p=new URLSearchParams(raw),hash=p.get("hash");if(!hash)return null;p.delete("hash");const pairs=[...p.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,v])=>k+"="+v).join("\n");const enc=new TextEncoder();const base=await crypto.subtle.importKey("raw",enc.encode("WebAppData"),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const secret=await crypto.subtle.sign("HMAC",base,enc.encode(token));const key=await crypto.subtle.importKey("raw",secret,{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,enc.encode(pairs));const hex=[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,"0")).join("");if(hex!==hash)return null;const u=p.get("user");try{return u?JSON.parse(u):null}catch{return null}}
async function ctx(request,env){const raw=request.headers.get("X-Telegram-Init-Data")||"";const user=await validInitData(raw,env.BOT_TOKEN);let admin=false;if(user){const ids=String(env.ADMIN_IDS||env.ADMIN_ID||"").split(",").map(x=>x.trim()).filter(Boolean);for(const id of ids){await env.DB.prepare("INSERT OR IGNORE INTO admins(telegram_id,role) VALUES(?,?)").bind(Number(id),"admin").run()}admin=ids.includes(String(user.id));if(!admin)admin=!!(await env.DB.prepare("SELECT 1 FROM admins WHERE telegram_id=?").bind(user.id).first())}return {user,isAdmin:admin}}
async function routes(env){const n=Number((await env.DB.prepare("SELECT COUNT(*) n FROM routes WHERE status='active'").first())?.n||0);if(n===0){const seed=[["Кия — Перяславка → Гродеково","Перяславка","Гродеково","Спокойный сплав по лесной части реки Кия","3 часа",2500],["Кия — Гродеково → Могилёвка","Гродеково","Могилёвка","Живописный маршрут по реке Кия","4 часа",2500],["Амур — закат","Амуркабель","Ерофей","Закатный SUP по живописным протокам Амура","2 часа",1500]];for(const x of seed)await env.DB.prepare("INSERT INTO routes(title,start_point,finish_point,description,duration,default_price,status) VALUES(?,?,?,?,?,?,'active')").bind(...x).run()}return (await env.DB.prepare("SELECT id,title,start_point,finish_point,default_price FROM routes WHERE status='active' ORDER BY id").all()).results||[]}
async function events(env,all=false){const q=all?"SELECT e.*,r.title route_title,r.start_point,r.finish_point FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.status='active' ORDER BY e.event_date,e.event_time":"SELECT e.*,r.title route_title,r.start_point,r.finish_point,MAX(0,e.max_places-(SELECT COUNT(*) FROM bookings b WHERE b.event_id=e.id AND b.status NOT IN ('cancelled','canceled'))) free_places FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.status='active' GROUP BY e.id ORDER BY e.event_date,e.event_time";return (await env.DB.prepare(q).all()).results||[]}
async function notify(env,text){if(!env.BOT_TOKEN||!env.ADMIN_ID)return;await fetch("https://api.telegram.org/bot"+env.BOT_TOKEN+"/sendMessage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:Number(env.ADMIN_ID),text})}).catch(()=>{})}
async function telegramSend(env,chatId,text,replyMarkup=null){
  if(!env.BOT_TOKEN)return;
  const body={chat_id:Number(chatId),text};
  if(replyMarkup)body.reply_markup=replyMarkup;
  await fetch("https://api.telegram.org/bot"+env.BOT_TOKEN+"/sendMessage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}).catch(()=>{});
}
async function webhookSecret(env){
  if(!env.BOT_TOKEN)return "";
  const enc=new TextEncoder();
  const key=await crypto.subtle.importKey("raw",enc.encode("webhook-secret"),{name:"HMAC",hash:"SHA-256"},false,["sign"]);
  const sig=await crypto.subtle.sign("HMAC",key,enc.encode(env.BOT_TOKEN));
  return [...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,"0")).join("");
}
async function handleTelegramWebhook(request,env){
  const expected=await webhookSecret(env);
  if(!expected||request.headers.get("X-Telegram-Bot-Api-Secret-Token")!==expected)return json({error:"Unauthorized"},401);
  const update=await request.json().catch(()=>null);
  const message=update?.message;
  if(!message?.chat?.id)return json({ok:true});
  const chatId=message.chat.id;
  const text=String(message.text||"");
  if(/^\/start(?:@\w+)?(?:\s|$)/i.test(text)){
    const appUrl=String(env.MINIAPP_URL||new URL(request.url).origin);
    await telegramSend(env,chatId,
      "🌊 Добро пожаловать в Wild East Club!\n\nСтирая границы, создавая моменты.\n\nОткройте приложение 👇",
      {inline_keyboard:[[{text:"🚀 Открыть Wild East Club",web_app:{url:appUrl}}]]}
    );
  }else if(/^\/admin(?:@\w+)?(?:\s|$)/i.test(text)){
    const userId=message.from?.id;
    const ids=String(env.ADMIN_IDS||env.ADMIN_ID||"").split(",").map(x=>x.trim()).filter(Boolean);for(const id of ids){await env.DB.prepare("INSERT OR IGNORE INTO admins(telegram_id,role) VALUES(?,?)").bind(Number(id),"admin").run()}const isAdmin=ids.includes(String(userId))||(userId&&!!(await env.DB.prepare("SELECT 1 FROM admins WHERE telegram_id=?").bind(userId).first()));
    if(isAdmin){
      const appUrl=String(env.MINIAPP_URL||new URL(request.url).origin);
      const adminUrl=new URL("/admin.html",appUrl).toString();
      await telegramSend(env,chatId,"👨‍💼 Административная панель",{
        inline_keyboard:[[{text:"Открыть админ-панель",web_app:{url:adminUrl}}]]
      });
    }else{
      await telegramSend(env,chatId,"⛔ Нет доступа.");
    }
  }
  return json({ok:true});
}
async function handle(request,env){const u=new URL(request.url),p=u.pathname,m=request.method;if(p==="/telegram/webhook"&&m==="POST")return handleTelegramWebhook(request,env);const c=await ctx(request,env);
if(p==="/api/events"&&m==="GET")return json({events:await events(env),routes:await routes(env),isAdmin:c.isAdmin});
if(p==="/api/bookings"&&m==="POST"){if(!c.user)return json({error:"Откройте приложение из Telegram"},401);const b=await request.json(),e=await env.DB.prepare("SELECT e.*,r.title route_title FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.id=? AND e.status='active'").bind(b.event_id).first();if(!e)return json({error:"Мероприятие недоступно"},404);const ps=Array.isArray(b.participants)?b.participants:[];if(!ps.length)return json({error:"Добавьте участника"},400);for(const x of ps){const ph=phone(x.phone);if(!String(x.full_name||"").trim()||!ph)return json({error:"Проверьте имя и телефон"},400);const d=await env.DB.prepare("SELECT 1 FROM bookings WHERE event_id=? AND lower(trim(full_name))=lower(trim(?)) AND phone=? AND status NOT IN ('cancelled','canceled')").bind(e.id,x.full_name,ph).first();if(d)return json({error:"Такая заявка уже существует"},409)}const occupied=Number((await env.DB.prepare("SELECT COUNT(*) n FROM bookings WHERE event_id=? AND status NOT IN ('cancelled','canceled')").bind(e.id).first())?.n||0);if(occupied+ps.length>Number(e.max_places||30))return json({error:"Недостаточно свободных мест"},409);const total=ps.reduce((s,x)=>s+Number(e.price||0)+(x.children?500:0),0);for(const x of ps){await env.DB.prepare("INSERT INTO bookings(event_id,telegram_id,full_name,phone,children,comment,status,source) VALUES(?,?,?,?,?,?,?,?)").bind(e.id,c.user.id,x.full_name,phone(x.phone),x.children?1:0,x.comment||"","new","miniapp").run()}await notify(env,"🔔 НОВЫЕ ЗАЯВКИ!\n🛶 "+(e.route_title||"Маршрут")+"\n📅 "+e.event_date+" "+e.event_time+"\nУчастников: "+ps.length+"\n💰 Итого: "+total+" ₽");return json({ok:true,count:ps.length,total})}
if(p==="/api/admin/bookings/manual"&&m==="POST"){if(!c.isAdmin)return json({error:"Нет доступа"},403);const b=await request.json(),ph=phone(b.phone);if(!String(b.full_name||"").trim()||!ph)return json({error:"Проверьте имя и телефон"},400);const e=await env.DB.prepare("SELECT e.*,r.title route_title FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.id=? AND e.status='active'").bind(b.event_id).first();if(!e)return json({error:"Мероприятие не найдено"},404);const dup=await env.DB.prepare("SELECT 1 FROM bookings WHERE event_id=? AND lower(trim(full_name))=lower(trim(?)) AND phone=? AND status NOT IN ('cancelled','canceled')").bind(e.id,b.full_name,ph).first();if(dup)return json({error:"Такая заявка уже существует"},409);const occupied=Number((await env.DB.prepare("SELECT COUNT(*) n FROM bookings WHERE event_id=? AND status NOT IN ('cancelled','canceled')").bind(e.id).first())?.n||0);if(occupied>=Number(e.max_places||30))return json({error:"Свободных мест нет"},409);await env.DB.prepare("INSERT INTO bookings(event_id,telegram_id,full_name,phone,children,comment,status,source) VALUES(?,?,?,?,?,?,?,?)").bind(e.id,c.user.id,b.full_name,ph,b.children?1:0,"","confirmed","manual").run();return json({ok:true,full_name:b.full_name,phone:ph,children:b.children?1:0})}
if(p==="/api/admin/bookings"&&m==="GET"){if(!c.isAdmin)return json({error:"Нет доступа"},403);const r=await env.DB.prepare("SELECT b.*,e.event_date,e.event_time,r.title route_title FROM bookings b LEFT JOIN events e ON e.id=b.event_id LEFT JOIN routes r ON r.id=e.route_id ORDER BY b.id DESC").all();return json({bookings:r.results||[]})}
if(/^\/api\/admin\/bookings\/\d+$/.test(p)&&m==="PATCH"){if(!c.isAdmin)return json({error:"Нет доступа"},403);await env.DB.prepare("UPDATE bookings SET status=? WHERE id=?").bind((await request.json()).status,Number(p.split("/").pop())).run();return json({ok:true})}
if(p==="/api/admin/routes"&&m==="GET"){if(!c.isAdmin)return json({error:"Нет доступа"},403);return json({routes:await routes(env)})}
if(p==="/api/admin/routes"&&m==="POST"){if(!c.isAdmin)return json({error:"Нет доступа"},403);const b=await request.json(),title=String(b.title||"").trim();if(!title)return json({error:"Укажите название маршрута"},400);const r=await env.DB.prepare("INSERT INTO routes(title,start_point,finish_point,description,duration,default_price,status) VALUES(?,?,?,?,?,?,'active') RETURNING id").bind(title,String(b.start_point||""),String(b.finish_point||""),String(b.description||""),String(b.duration||""),Number(b.default_price||0)).first();return json({ok:true,id:r.id})}
if(/^\/api\/admin\/routes\/\d+$/.test(p)){if(!c.isAdmin)return json({error:"Нет доступа"},403);const id=Number(p.split("/").pop());if(m==="PUT"){const b=await request.json(),title=String(b.title||"").trim();if(!title)return json({error:"Укажите название маршрута"},400);await env.DB.prepare("UPDATE routes SET title=?,start_point=?,finish_point=?,description=?,duration=?,default_price=? WHERE id=?").bind(title,String(b.start_point||""),String(b.finish_point||""),String(b.description||""),String(b.duration||""),Number(b.default_price||0),id).run();return json({ok:true})}if(m==="DELETE"){const used=await env.DB.prepare("SELECT 1 FROM events WHERE route_id=? AND status='active' LIMIT 1").bind(id).first();if(used)return json({error:"Нельзя удалить маршрут с активными мероприятиями"},409);await env.DB.prepare("UPDATE routes SET status='deleted' WHERE id=?").bind(id).run();return json({ok:true})}}
if(p==="/api/admin/events"&&m==="GET"){if(!c.isAdmin)return json({error:"Нет доступа"},403);return json({events:await events(env,true),routes:await routes(env)})}
if(p==="/api/admin/events"&&m==="POST"){if(!c.isAdmin)return json({error:"Нет доступа"},403);const b=await request.json(),r=await env.DB.prepare("INSERT INTO events(route_id,event_date,event_time,price,max_places,free_places,meeting_point,status) VALUES(?,?,?,?,?,?,?,'active') RETURNING id").bind(b.route_id,b.event_date,b.event_time,Number(b.price),Math.max(1,Number(b.max_places||30)),Math.max(1,Number(b.max_places||30)),b.meeting_point||"").first();return json({ok:true,id:r.id})}
if(/^\/api\/admin\/events\/\d+$/.test(p)){if(!c.isAdmin)return json({error:"Нет доступа"},403);const id=Number(p.split("/").pop());if(m==="PUT"){const b=await request.json(),max=Math.max(1,Number(b.max_places||30));const occupied=Number((await env.DB.prepare("SELECT COUNT(*) n FROM bookings WHERE event_id=? AND status NOT IN ('cancelled','canceled')").bind(id).first())?.n||0);if(max<occupied)return json({error:"Лимит мест не может быть меньше уже занятых мест"},409);await env.DB.prepare("UPDATE events SET route_id=?,event_date=?,event_time=?,price=?,max_places=?,free_places=?,meeting_point=? WHERE id=?").bind(b.route_id,b.event_date,b.event_time,Number(b.price),max,Math.max(0,max-occupied),b.meeting_point||"",id).run();return json({ok:true})}if(m==="DELETE"){await env.DB.prepare("UPDATE events SET status='deleted' WHERE id=?").bind(id).run();return json({ok:true})}}
if(/^\/api\/admin\/reports\/\d+$/.test(p)&&m==="GET"){if(!c.isAdmin)return json({error:"Нет доступа"},403);const id=Number(p.split("/").pop()),e=await env.DB.prepare("SELECT e.*,r.title route_title FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.id=?").bind(id).first();if(!e)return json({error:"Мероприятие не найдено"},404);const rows=(await env.DB.prepare("SELECT b.id,b.full_name,b.phone,b.children,b.status,e.event_date,e.event_time,e.price,r.title route_title FROM bookings b JOIN events e ON e.id=b.event_id LEFT JOIN routes r ON r.id=e.route_id WHERE b.event_id=? AND b.status NOT IN ('cancelled','canceled') ORDER BY e.event_date,e.event_time,b.id") .bind(id).all()).results||[];const bs=rows.map(b=>({...b,revenue:Number(b.price||0)+Number(b.children||0)*500}));return json({event_id:id,route_title:e.route_title,bookings:bs,total_people:bs.reduce((s,b)=>s+1+Number(b.children||0),0),total_boards:bs.length,total_revenue:bs.reduce((s,b)=>s+b.revenue,0)})}
if(p==="/api/admin/reports"&&m==="GET"){if(!c.isAdmin)return json({error:"Нет доступа"},403);const groups=(await env.DB.prepare("SELECT b.event_id event_id,MIN(e.event_date) event_date,MIN(e.event_time) event_time,COALESCE(r.title,'Маршрут не указан') route_title,COUNT(*) boards,SUM(1+COALESCE(b.children,0)) people,SUM(COALESCE(e.price,0)+COALESCE(b.children,0)*500) revenue FROM bookings b JOIN events e ON e.id=b.event_id LEFT JOIN routes r ON r.id=e.route_id WHERE b.status NOT IN ('cancelled','canceled') GROUP BY b.event_id,e.event_date,e.event_time,r.title ORDER BY MIN(e.event_date),MIN(e.event_time)").all()).results||[];return json({groups})}
return null}
export default {async fetch(request,env){const r=await handle(request,env);return r||env.ASSETS.fetch(request)}};