const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
function phone(v){let d=String(v||"").replace(/\\D/g,"");if(d.length===11&&d[0]==="8")d="7"+d.slice(1);if(d.length===10)d="7"+d;return /^7\\d{10}$/.test(d)?"+"+d:null}
async function ctx(request,env){const raw=request.headers.get("X-Telegram-Init-Data")||"";const p=new URLSearchParams(raw),u=p.get("user");let user=null;try{user=u?JSON.parse(u):null}catch{};let admin=false;if(user){admin=String(user.id)===String(env.ADMIN_ID);if(!admin)admin=!!(await env.DB.prepare("SELECT 1 FROM admins WHERE telegram_id=?").bind(user.id).first())}return {user,isAdmin:admin}}
async function routes(env){return (await env.DB.prepare("SELECT id,title,start_point,finish_point,default_price FROM routes WHERE status='active' ORDER BY id").all()).results||[]}
async function events(env,all=false){const q=all?"SELECT e.*,r.title route_title,r.start_point,r.finish_point FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.status='active' ORDER BY e.event_date,e.event_time":"SELECT e.*,r.title route_title,r.start_point,r.finish_point,MAX(0,e.max_places-(SELECT COUNT(*) FROM bookings b WHERE b.event_id=e.id AND b.status NOT IN ('cancelled','canceled'))) free_places FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.status='active' GROUP BY e.id ORDER BY e.event_date,e.event_time";return (await env.DB.prepare(q).all()).results||[]}
async function notify(env,text){if(!env.BOT_TOKEN||!env.ADMIN_ID)return;await fetch("https://api.telegram.org/bot"+env.BOT_TOKEN+"/sendMessage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:Number(env.ADMIN_ID),text})}).catch(()=>{})}
async function handle(request,env){const u=new URL(request.url),p=u.pathname,m=request.method,c=await ctx(request,env);
if(p==="/api/events"&&m==="GET")return json({events:await events(env),routes:await routes(env),isAdmin:c.isAdmin});
if(p==="/api/bookings"&&m==="POST"){if(!c.user)return json({error:"Откройте приложение из Telegram"},401);const b=await request.json(),e=await env.DB.prepare("SELECT e.*,r.title route_title FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.id=? AND e.status='active'").bind(b.event_id).first();if(!e)return json({error:"Мероприятие недоступно"},404);const ps=Array.isArray(b.participants)?b.participants:[];if(!ps.length)return json({error:"Добавьте участника"},400);for(const x of ps){const ph=phone(x.phone);if(!String(x.full_name||"").trim()||!ph)return json({error:"Проверьте имя и телефон"},400);const d=await env.DB.prepare("SELECT 1 FROM bookings WHERE event_id=? AND lower(trim(full_name))=lower(trim(?)) AND phone=? AND status NOT IN ('cancelled','canceled')").bind(e.id,x.full_name,ph).first();if(d)return json({error:"Такая заявка уже существует"},409)}const total=ps.reduce((s,x)=>s+Number(e.price||0)+(x.children?500:0),0);for(const x of ps){await env.DB.prepare("INSERT INTO bookings(event_id,telegram_id,full_name,phone,children,comment,status,source) VALUES(?,?,?,?,?,?,?,?)").bind(e.id,c.user.id,x.full_name,phone(x.phone),x.children?1:0,x.comment||"","new","miniapp").run()}await notify(env,"🔔 НОВЫЕ ЗАЯВКИ!\n🛶 "+(e.route_title||"Маршрут")+"\n📅 "+e.event_date+" "+e.event_time+"\nУчастников: "+ps.length+"\n💰 Итого: "+total+" ₽");return json({ok:true,count:ps.length,total})}
if(p==="/api/admin/bookings"&&m==="GET"){if(!c.isAdmin)return json({error:"Нет доступа"},403);const r=await env.DB.prepare("SELECT b.*,e.event_date,e.event_time,r.title route_title FROM bookings b LEFT JOIN events e ON e.id=b.event_id LEFT JOIN routes r ON r.id=e.route_id ORDER BY b.id DESC").all();return json({bookings:r.results||[]})}
if(/^\/api\/admin\/bookings\/\d+$/.test(p)&&m==="PATCH"){if(!c.isAdmin)return json({error:"Нет доступа"},403);await env.DB.prepare("UPDATE bookings SET status=? WHERE id=?").bind((await request.json()).status,Number(p.split("/").pop())).run();return json({ok:true})}
if(p==="/api/admin/events"&&m==="GET"){if(!c.isAdmin)return json({events:await events(env,true),routes:await routes(env)})}
if(p==="/api/admin/events"&&m==="POST"){if(!c.isAdmin)return json({error:"Нет доступа"},403);const b=await request.json(),r=await env.DB.prepare("INSERT INTO events(route_id,event_date,event_time,price,max_places,free_places,meeting_point,status) VALUES(?,?,?,?,30,30,?,'active') RETURNING id").bind(b.route_id,b.event_date,b.event_time,Number(b.price),b.meeting_point||"").first();return json({ok:true,id:r.id})}
if(/^\/api\/admin\/events\/\d+$/.test(p)){if(!c.isAdmin)return json({error:"Нет доступа"},403);const id=Number(p.split("/").pop());if(m==="PUT"){const b=await request.json();await env.DB.prepare("UPDATE events SET route_id=?,event_date=?,event_time=?,price=?,meeting_point=? WHERE id=?").bind(b.route_id,b.event_date,b.event_time,Number(b.price),b.meeting_point||"",id).run();return json({ok:true})}if(m==="DELETE"){await env.DB.prepare("UPDATE events SET status='deleted' WHERE id=?").bind(id).run();return json({ok:true})}}
if(p==="/api/admin/reports"&&m==="GET"){if(!c.isAdmin)return json({error:"Нет доступа"},403);const r=await env.DB.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status='confirmed' THEN 1 ELSE 0 END) confirmed,SUM(CASE WHEN status='new' THEN 1 ELSE 0 END) new,SUM(CASE WHEN status IN ('cancelled','canceled') THEN 1 ELSE 0 END) cancelled FROM bookings").first();return json(r)}
return null}
export default {async fetch(request,env){const r=await handle(request,env);return r||env.ASSETS.fetch(request)}};