const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
function phone(v){let d=String(v||"").replace(/\D/g,"");if(d.length===11&&d[0]==="8")d="7"+d.slice(1);if(d.length===10)d="7"+d;return /^7\d{10}$/.test(d)?"+"+d:null}
async function validInitData(raw,token){if(!raw||!token)return null;const p=new URLSearchParams(raw),hash=p.get("hash");if(!hash)return null;p.delete("hash");const pairs=[...p.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,v])=>k+"="+v).join("\n");const enc=new TextEncoder();const base=await crypto.subtle.importKey("raw",enc.encode("WebAppData"),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const secret=await crypto.subtle.sign("HMAC",base,enc.encode(token));const key=await crypto.subtle.importKey("raw",secret,{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,enc.encode(pairs));const hex=[...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,"0")).join("");if(hex!==hash)return null;const u=p.get("user");try{return u?JSON.parse(u):null}catch{return null}}
const ALL_PERMS=["bookings","events","reports","media","admins"];
const ROLE_PERMS={owner:ALL_PERMS,admin:ALL_PERMS,manager:["bookings","events","reports"],content:["media"],viewer:["bookings","reports"]};
function rowPerms(row){if(!row)return[];try{const p=JSON.parse(row.permissions||"[]");if(Array.isArray(p)&&p.length)return p}catch{}return ROLE_PERMS[row.role]||ROLE_PERMS.viewer}
function hasPerm(c,p){return !!c?.isAdmin&&(c.permissions||[]).includes(p)}
async function ctx(request,env){const raw=request.headers.get("X-Telegram-Init-Data")||"";const user=await validInitData(raw,env.BOT_TOKEN);let admin=false,permissions=[];if(user){const ids=String(env.ADMIN_IDS||env.ADMIN_ID||"").split(",").map(x=>x.trim()).filter(Boolean);for(const id of ids){await env.DB.prepare("INSERT OR IGNORE INTO admins(telegram_id,role,permissions) VALUES(?,?,?)").bind(Number(id),"owner",JSON.stringify(ALL_PERMS)).run()}const row=await env.DB.prepare("SELECT telegram_id,role,permissions FROM admins WHERE telegram_id=?").bind(user.id).first();admin=!!row;permissions=rowPerms(row)}return {user,isAdmin:admin,permissions}}
async function routes(env){const n=Number((await env.DB.prepare("SELECT COUNT(*) n FROM routes WHERE status='active'").first())?.n||0);if(n===0){const seed=[["Кия — Перяславка → Гродеково","sup","Перяславка","Гродеково","Спокойный сплав по лесной части реки Кия","3 часа",2500],["Кия — Гродеково → Могилёвка","sup","Гродеково","Могилёвка","Живописный маршрут по реке Кия","4 часа",2500],["Амур — закат","sup","Амуркабель","Ерофей","Закатный SUP по живописным протокам Амура","2 часа",1500],["Хехцир пешие маршруты","hiking","Хехцир","Хехцир","Пешие маршруты по лесу Хехцира","3–5 часов",1500]];for(const x of seed)await env.DB.prepare("INSERT INTO routes(title,type,start_point,finish_point,description,duration,default_price,status) VALUES(?,?,?,?,?,?,?,'active')").bind(...x).run()}else{const exists=await env.DB.prepare("SELECT 1 FROM routes WHERE title=? AND status='active'").bind("Хехцир пешие маршруты").first();if(!exists)await env.DB.prepare("INSERT INTO routes(title,type,start_point,finish_point,description,duration,default_price,status) VALUES(?,?,?,?,?,?,?,'active')").bind("Хехцир пешие маршруты","hiking","Хехцир","Хехцир","Пешие маршруты по лесу Хехцира","3–5 часов",1500).run()}return (await env.DB.prepare("SELECT id,title,type,start_point,finish_point,default_price,image_key FROM routes WHERE status='active' ORDER BY id").all()).results||[]}
async function events(env,all=false){const q=all?"SELECT e.*,r.title route_title,r.type route_type,r.start_point,r.finish_point,r.image_key route_image_key FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.status='active' ORDER BY e.event_date,e.event_time":"SELECT e.*,r.title route_title,r.type route_type,r.start_point,r.finish_point,r.image_key route_image_key,MAX(0,e.max_places-(SELECT COUNT(*) FROM bookings b WHERE b.event_id=e.id AND b.status NOT IN ('cancelled','canceled'))) free_places FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.status='active' GROUP BY e.id ORDER BY e.event_date,e.event_time";return (await env.DB.prepare(q).all()).results||[]}
async function notify(env,text){if(!env.BOT_TOKEN)return;const ids=String(env.ADMIN_IDS||env.ADMIN_ID||"").split(",").map(x=>x.trim()).filter(Boolean);for(const id of ids)await fetch("https://api.telegram.org/bot"+env.BOT_TOKEN+"/sendMessage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:Number(id),text})}).catch(()=>{})}
async function telegramSend(env,chatId,text,replyMarkup=null){
  if(!env.BOT_TOKEN)return;
  const body={chat_id:Number(chatId),text};
  if(replyMarkup)body.reply_markup=replyMarkup;
  await fetch("https://api.telegram.org/bot"+env.BOT_TOKEN+"/sendMessage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}).catch(()=>{});
}
async function webhookSecret(env){
  if(!env.BOT_TOKEN)return "";
  const enc=new TextEncoder();
  const key=await crypto.subtle.importKey("raw",enc.encode("webhook-secret"),{name:"HMAC",hash:"SHA-256"},false,["sign"]);
  const sig=await crypto.subtle.sign("HMAC",key,enc.encode(env.BOT_TOKEN));
  return [...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,"0")).join("");
}
async function handleTelegramWebhook(request,env){
  const expected=await webhookSecret(env);
  if(!expected||request.headers.get("X-Telegram-Bot-Api-Secret-Token")!==expected)return json({error:"Unauthorized"},401);
  const update=await request.json().catch(()=>null);
  const message=update?.message;
  if(!message?.chat?.id)return json({ok:true});
  const chatId=message.chat.id;
  if(message.contact?.phone_number && message.from?.id && Number(message.contact.user_id||message.from.id)===Number(message.from.id)){
    await env.DB.prepare("CREATE TABLE IF NOT EXISTS user_profiles(telegram_id INTEGER PRIMARY KEY,phone TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();
    const ph=phone(message.contact.phone_number);
    if(ph)await env.DB.prepare("INSERT INTO user_profiles(telegram_id,phone,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(telegram_id) DO UPDATE SET phone=excluded.phone,updated_at=CURRENT_TIMESTAMP").bind(Number(message.from.id),ph).run();
    return json({ok:true});
  }
  const text=String(message.text||"");
  if(/^\/start(?:@\w+)?(?:\s|$)/i.test(text)){
    const appUrl=String(env.MINIAPP_URL||new URL(request.url).origin);
    await telegramSend(env,chatId,
      "🌊 Добро пожаловать в Wild East Club!\n\nСтирая границы, создавая моменты.\n\nОткройте приложение 👇",
      {inline_keyboard:[[{text:"🚀 Открыть Wild East Club",web_app:{url:appUrl}}]]}
    );
  }else if(/^\/admin(?:@\w+)?(?:\s|$)/i.test(text)){
    const userId=message.from?.id;
    const ids=String(env.ADMIN_IDS||env.ADMIN_ID||"").split(",").map(x=>x.trim()).filter(Boolean);for(const id of ids){await env.DB.prepare("INSERT OR IGNORE INTO admins(telegram_id,role) VALUES(?,?)").bind(Number(id),"admin").run()}const isAdmin=ids.includes(String(userId))||(userId&&!!(await env.DB.prepare("SELECT 1 FROM admins WHERE telegram_id=?").bind(userId).first()));
    if(isAdmin){
      const appUrl=String(env.MINIAPP_URL||new URL(request.url).origin);
      const adminUrl=new URL("/admin.html",appUrl).toString();
      await telegramSend(env,chatId,"👨‍💼 Административная панель",{
        inline_keyboard:[[{text:"Открыть админ-панель",web_app:{url:adminUrl}}]]
      });
    }else{
      await telegramSend(env,chatId,"⛔ Нет доступа.");
    }
  }
  return json({ok:true});
}
async function handle(request,env){const u=new URL(request.url),p=u.pathname,m=request.method;if(p==="/telegram/webhook"&&m==="POST")return handleTelegramWebhook(request,env);const c=await ctx(request,env);
if(p==="/api/events"&&m==="GET"){const es=await events(env),rs=await routes(env),s=await env.DB.prepare("SELECT value FROM app_settings WHERE key='home_image_key'").first();const homeKey=s?.value||"";const base=new URL(request.url).origin;return json({events:es.map(e=>({...e,route_image_url:e.route_image_key?base+"/media/"+e.route_image_key:null})),routes:rs,isAdmin:c.isAdmin,home_image_url:homeKey?base+"/media/"+homeKey:null,permissions:c.permissions||[]});}
if(p==="/api/profile"&&m==="GET"){if(!c.user)return json({error:"Откройте приложение из Telegram"},401);await env.DB.prepare("CREATE TABLE IF NOT EXISTS user_profiles(telegram_id INTEGER PRIMARY KEY,phone TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();const r=await env.DB.prepare("SELECT phone FROM user_profiles WHERE telegram_id=?").bind(c.user.id).first();return json({phone:r?.phone||""})}
if(p==="/api/bookings"&&m==="POST"){if(!c.user)return json({error:"Откройте приложение из Telegram"},401);const b=await request.json(),e=await env.DB.prepare("SELECT e.*,r.title route_title FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.id=? AND e.status='active'").bind(b.event_id).first();if(!e)return json({error:"Мероприятие недоступно"},404);const ps=Array.isArray(b.participants)?b.participants:[];if(!ps.length)return json({error:"Добавьте участника"},400);for(const x of ps){const ph=phone(x.phone);if(!String(x.full_name||"").trim()||!ph)return json({error:"Проверьте имя и телефон"},400);const d=await env.DB.prepare("SELECT 1 FROM bookings WHERE event_id=? AND lower(trim(full_name))=lower(trim(?)) AND phone=? AND status NOT IN ('cancelled','canceled')").bind(e.id,x.full_name,ph).first();if(d)return json({error:"Такая заявка уже существует"},409)}const occupied=Number((await env.DB.prepare("SELECT COUNT(*) n FROM bookings WHERE event_id=? AND status NOT IN ('cancelled','canceled')").bind(e.id).first())?.n||0);if(occupied+ps.length>Number(e.max_places||30))return json({error:"Недостаточно свободных мест"},409);const total=ps.reduce((s,x)=>s+Number(e.price||0)+(x.children?500:0),0);for(const x of ps){await env.DB.prepare("INSERT INTO bookings(event_id,telegram_id,full_name,phone,children,comment,status,source) VALUES(?,?,?,?,?,?,?,?)").bind(e.id,c.user.id,x.full_name,phone(x.phone),x.children?1:0,x.comment||"","new","miniapp").run()}await notify(env,"🔔 НОВЫЕ ЗАЯВКИ!\n🛶 "+(e.route_title||"Маршрут")+"\n📅 "+e.event_date+" "+e.event_time+"\nУчастников: "+ps.length+"\n💰 Итого: "+total+" ₽");return json({ok:true,count:ps.length,total})}
if(p==="/api/admin/bookings/manual"&&m==="POST"){if(!hasPerm(c,"bookings"))return json({error:"Нет доступа"},403);const b=await request.json(),ph=phone(b.phone);if(!String(b.full_name||"").trim()||!ph)return json({error:"Проверьте имя и телефон"},400);const e=await env.DB.prepare("SELECT e.*,r.title route_title FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.id=? AND e.status='active'").bind(b.event_id).first();if(!e)return json({error:"Мероприятие не найдено"},404);const dup=await env.DB.prepare("SELECT 1 FROM bookings WHERE event_id=? AND lower(trim(full_name))=lower(trim(?)) AND phone=? AND status NOT IN ('cancelled','canceled')").bind(e.id,b.full_name,ph).first();if(dup)return json({error:"Такая заявка уже существует"},409);const occupied=Number((await env.DB.prepare("SELECT COUNT(*) n FROM bookings WHERE event_id=? AND status NOT IN ('cancelled','canceled')").bind(e.id).first())?.n||0);if(occupied>=Number(e.max_places||30))return json({error:"Свободных мест нет"},409);await env.DB.prepare("INSERT INTO bookings(event_id,telegram_id,full_name,phone,children,comment,status,source) VALUES(?,?,?,?,?,?,?,?)").bind(e.id,c.user.id,b.full_name,ph,b.children?1:0,"","confirmed","manual").run();return json({ok:true,full_name:b.full_name,phone:ph,children:b.children?1:0})}
if(p==="/api/admin/bookings"&&m==="GET"){if(!hasPerm(c,"bookings"))return json({error:"Нет доступа"},403);const r=await env.DB.prepare("SELECT b.*,e.event_date,e.event_time,r.title route_title FROM bookings b LEFT JOIN events e ON e.id=b.event_id LEFT JOIN routes r ON r.id=e.route_id ORDER BY b.id DESC").all();return json({bookings:r.results||[]})}
if(/^\/api\/admin\/bookings\/\d+$/.test(p)&&m==="PATCH"){if(!hasPerm(c,"bookings"))return json({error:"Нет доступа"},403);await env.DB.prepare("UPDATE bookings SET status=? WHERE id=?").bind((await request.json()).status,Number(p.split("/").pop())).run();return json({ok:true})}
if(p==="/api/admin/event-templates"&&m==="GET"){if(!hasPerm(c,"events"))return json({error:"Нет доступа"},403);const r=await env.DB.prepare("SELECT t.*,r.title route_title,r.type route_type,r.start_point,r.finish_point FROM event_templates t LEFT JOIN routes r ON r.id=t.route_id WHERE t.status='active' ORDER BY t.id DESC").all();return json({templates:r.results||[]})}
if(p==="/api/admin/event-templates"&&m==="POST"){if(!hasPerm(c,"events"))return json({error:"Нет доступа"},403);const b=await request.json(),name=String(b.name||"").trim(),routeId=Number(b.route_id||0);if(!name||!routeId)return json({error:"Укажите название шаблона и маршрут"},400);const r=await env.DB.prepare("INSERT INTO event_templates(name,route_id,event_time,price,max_places,meeting_point,status) VALUES(?,?,?,?,?,?,'active') RETURNING id").bind(name,routeId,String(b.event_time||""),Number(b.price||0),Math.max(1,Number(b.max_places||30)),String(b.meeting_point||"")).first();return json({ok:true,id:r.id})}
if(/^\/api\/admin\/event-templates\/\d+$/.test(p)){if(!hasPerm(c,"events"))return json({error:"Нет доступа"},403);const id=Number(p.split("/").pop());if(m==="PUT"){const b=await request.json(),name=String(b.name||"").trim(),routeId=Number(b.route_id||0);if(!name||!routeId)return json({error:"Укажите название шаблона и маршрут"},400);await env.DB.prepare("UPDATE event_templates SET name=?,route_id=?,event_time=?,price=?,max_places=?,meeting_point=? WHERE id=?").bind(name,routeId,String(b.event_time||""),Number(b.price||0),Math.max(1,Number(b.max_places||30)),String(b.meeting_point||""),id).run();return json({ok:true})}if(m==="DELETE"){await env.DB.prepare("UPDATE event_templates SET status='deleted' WHERE id=?").bind(id).run();return json({ok:true})}}
if(p==="/api/admin/routes"&&m==="GET"){if(!hasPerm(c,"events"))return json({error:"Нет доступа"},403);return json({routes:await routes(env)})}
if(p==="/api/admin/routes"&&m==="POST"){if(!hasPerm(c,"events"))return json({error:"Нет доступа"},403);const b=await request.json(),title=String(b.title||"").trim(),type=String(b.type||"sup")==="hiking"?"hiking":"sup";if(!title)return json({error:"Укажите название маршрута"},400);const r=await env.DB.prepare("INSERT INTO routes(title,type,start_point,finish_point,description,duration,default_price,status) VALUES(?,?,?,?,?,?,?,'active') RETURNING id").bind(title,type,String(b.start_point||""),String(b.finish_point||""),String(b.description||""),String(b.duration||""),Number(b.default_price||0)).first();return json({ok:true,id:r.id})}
if(/^\/api\/admin\/routes\/\d+$/.test(p)){if(!hasPerm(c,"events"))return json({error:"Нет доступа"},403);const id=Number(p.split("/").pop());if(m==="PUT"){const b=await request.json(),title=String(b.title||"").trim(),type=String(b.type||"sup")==="hiking"?"hiking":"sup";if(!title)return json({error:"Укажите название маршрута"},400);await env.DB.prepare("UPDATE routes SET title=?,type=?,start_point=?,finish_point=?,description=?,duration=?,default_price=? WHERE id=?").bind(title,type,String(b.start_point||""),String(b.finish_point||""),String(b.description||""),String(b.duration||""),Number(b.default_price||0),id).run();return json({ok:true})}if(m==="DELETE"){const used=await env.DB.prepare("SELECT 1 FROM events WHERE route_id=? AND status='active' LIMIT 1").bind(id).first();if(used)return json({error:"Нельзя удалить маршрут с активными мероприятиями"},409);await env.DB.prepare("UPDATE routes SET status='deleted' WHERE id=?").bind(id).run();return json({ok:true})}}
if(p==="/api/admin/events"&&m==="GET"){if(!hasPerm(c,"events"))return json({error:"Нет доступа"},403);return json({events:await events(env,true),routes:await routes(env)})}
if(p==="/api/admin/events"&&m==="POST"){if(!hasPerm(c,"events"))return json({error:"Нет доступа"},403);const b=await request.json(),routeId=Number(b.route_id||0);if(!routeId)return json({error:"Выберите шаблон мероприятия"},400);const r=await env.DB.prepare("INSERT INTO events(route_id,event_date,event_time,price,max_places,free_places,meeting_point,status) VALUES(?,?,?,?,?,?,?,'active') RETURNING id").bind(routeId,b.event_date,String(b.event_time||""),Number(b.price||0),Math.max(1,Number(b.max_places||30)),Math.max(1,Number(b.max_places||30)),String(b.meeting_point||"")).first();return json({ok:true,id:r.id})}
if(/^\/api\/admin\/events\/\d+$/.test(p)){if(!hasPerm(c,"events"))return json({error:"Нет доступа"},403);const id=Number(p.split("/").pop());if(m==="PUT"){const b=await request.json(),max=Math.max(1,Number(b.max_places||30));const occupied=Number((await env.DB.prepare("SELECT COUNT(*) n FROM bookings WHERE event_id=? AND status NOT IN ('cancelled','canceled')").bind(id).first())?.n||0);if(max<occupied)return json({error:"Лимит мест не может быть меньше уже занятых мест"},409);await env.DB.prepare("UPDATE events SET route_id=?,event_date=?,event_time=?,price=?,max_places=?,free_places=?,meeting_point=? WHERE id=?").bind(b.route_id,b.event_date,b.event_time,Number(b.price),max,Math.max(0,max-occupied),b.meeting_point||"",id).run();return json({ok:true})}if(m==="DELETE"){await env.DB.prepare("UPDATE events SET status='deleted' WHERE id=?").bind(id).run();return json({ok:true})}}
if(p==="/api/admin/reports/summary"&&m==="GET"){if(!hasPerm(c,"reports"))return json({error:"Нет доступа"},403);const from=u.searchParams.get("from")||"0000-01-01",to=u.searchParams.get("to")||"9999-12-31";const r=await env.DB.prepare("SELECT COUNT(DISTINCT b.event_id) events,COUNT(*) bookings,SUM(1+COALESCE(b.children,0)) people,SUM(COALESCE(e.price,0)+COALESCE(b.children,0)*500) revenue FROM bookings b JOIN events e ON e.id=b.event_id WHERE b.status NOT IN ('cancelled','canceled') AND e.event_date BETWEEN ? AND ?").bind(from,to).first();return json({from,to,summary:r||{events:0,bookings:0,people:0,revenue:0}})}
if(p==="/api/admin/reports/archive"&&m==="POST"){if(!hasPerm(c,"reports"))return json({error:"Нет доступа"},403);await env.DB.prepare("CREATE TABLE IF NOT EXISTS report_snapshots(event_id INTEGER PRIMARY KEY,route_title TEXT,event_date TEXT,event_time TEXT,total_people INTEGER,total_boards INTEGER,total_revenue INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP)").run();const b=await request.json(),e=await env.DB.prepare("SELECT e.*,r.title route_title FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.id=?").bind(Number(b.event_id)).first();if(!e)return json({error:"Мероприятие не найдено"},404);const s=await env.DB.prepare("SELECT COUNT(*) boards,SUM(1+COALESCE(b.children,0)) people,SUM(COALESCE(e.price,0)+COALESCE(b.children,0)*500) revenue FROM bookings b JOIN events e ON e.id=b.event_id WHERE b.event_id=? AND b.status NOT IN ('cancelled','canceled')").bind(e.id).first();await env.DB.prepare("INSERT INTO report_snapshots(event_id,route_title,event_date,event_time,total_people,total_boards,total_revenue) VALUES(?,?,?,?,?,?,?) ON CONFLICT(event_id) DO UPDATE SET route_title=excluded.route_title,event_date=excluded.event_date,event_time=excluded.event_time,total_people=excluded.total_people,total_boards=excluded.total_boards,total_revenue=excluded.total_revenue").bind(e.id,e.route_title,e.event_date,e.event_time,Number(s?.people||0),Number(s?.boards||0),Number(s?.revenue||0)).run();return json({ok:true})}
if(/^\/api\/admin\/reports\/\d+$/.test(p)&&m==="GET"){if(!hasPerm(c,"reports"))return json({error:"Нет доступа"},403);const id=Number(p.split("/").pop()),e=await env.DB.prepare("SELECT e.*,r.title route_title FROM events e LEFT JOIN routes r ON r.id=e.route_id WHERE e.id=?").bind(id).first();if(!e)return json({error:"Мероприятие не найдено"},404);const rows=(await env.DB.prepare("SELECT b.id,b.full_name,b.phone,b.children,b.status,e.event_date,e.event_time,e.price,r.title route_title FROM bookings b JOIN events e ON e.id=b.event_id LEFT JOIN routes r ON r.id=e.route_id WHERE b.event_id=? AND b.status NOT IN ('cancelled','canceled') ORDER BY e.event_date,e.event_time,b.id") .bind(id).all()).results||[];const bs=rows.map(b=>({...b,revenue:Number(b.price||0)+Number(b.children||0)*500}));return json({event_id:id,route_title:e.route_title,bookings:bs,total_people:bs.reduce((s,b)=>s+1+Number(b.children||0),0),total_boards:bs.length,total_revenue:bs.reduce((s,b)=>s+b.revenue,0)})}
if(p==="/api/admin/reports"&&m==="GET"){if(!hasPerm(c,"reports"))return json({error:"Нет доступа"},403);const groups=(await env.DB.prepare("SELECT b.event_id event_id,MIN(e.event_date) event_date,MIN(e.event_time) event_time,COALESCE(r.title,'Маршрут не указан') route_title,COUNT(*) boards,SUM(1+COALESCE(b.children,0)) people,SUM(COALESCE(e.price,0)+COALESCE(b.children,0)*500) revenue FROM bookings b JOIN events e ON e.id=b.event_id LEFT JOIN routes r ON r.id=e.route_id WHERE b.status NOT IN ('cancelled','canceled') GROUP BY b.event_id,e.event_date,e.event_time,r.title ORDER BY MIN(e.event_date),MIN(e.event_time)").all()).results||[];return json({groups})}

if(p==="/api/admin/settings"&&m==="GET"){if(!hasPerm(c,"media")&&!hasPerm(c,"admins"))return json({error:"Нет доступа"},403);const home=await env.DB.prepare("SELECT value FROM app_settings WHERE key='home_image_key'").first();const rs=await routes(env);let admins=[];if(hasPerm(c,"admins"))admins=(await env.DB.prepare("SELECT telegram_id,role,permissions FROM admins ORDER BY telegram_id").all()).results||[];return json({home_image_key:home?.value||"",home_image_url:home?.value?new URL("/media/"+home.value,request.url).toString():null,routes:rs,admins:admins.map(x=>({...x,permissions:rowPerms(x)})),permissions:c.permissions||[]})}
if(p==="/api/admin/admins"&&m==="GET"){if(!hasPerm(c,"admins"))return json({error:"Нет доступа"},403);const rows=(await env.DB.prepare("SELECT telegram_id,role,permissions FROM admins ORDER BY telegram_id").all()).results||[];return json({admins:rows.map(x=>({...x,permissions:rowPerms(x)}))})}
if(p==="/api/admin/admins"&&m==="POST"){if(!hasPerm(c,"admins"))return json({error:"Нет доступа"},403);const b=await request.json(),id=Number(b.telegram_id||0),role=String(b.role||"manager");if(!id)return json({error:"Укажите Telegram ID"},400);const perms=Array.isArray(b.permissions)?b.permissions.filter(x=>ALL_PERMS.includes(x)):[];await env.DB.prepare("INSERT INTO admins(telegram_id,role,permissions) VALUES(?,?,?) ON CONFLICT(telegram_id) DO UPDATE SET role=excluded.role,permissions=excluded.permissions").bind(id,role,JSON.stringify(perms)).run();return json({ok:true})}
if(/^\/api\/admin\/admins\/\d+$/.test(p)){if(!hasPerm(c,"admins"))return json({error:"Нет доступа"},403);const id=Number(p.split("/").pop());if(id===Number(c.user?.id))return json({error:"Нельзя изменять собственные права из этого раздела"},409);if(m==="PUT"){const b=await request.json(),role=String(b.role||"manager"),perms=Array.isArray(b.permissions)?b.permissions.filter(x=>ALL_PERMS.includes(x)):[];await env.DB.prepare("UPDATE admins SET role=?,permissions=? WHERE telegram_id=?").bind(role,JSON.stringify(perms),id).run();return json({ok:true})}if(m==="DELETE"){const protectedIds=String(env.ADMIN_IDS||env.ADMIN_ID||"").split(",").map(x=>Number(x));if(protectedIds.includes(id))return json({error:"Основного администратора нельзя удалить"},409);await env.DB.prepare("DELETE FROM admins WHERE telegram_id=?").bind(id).run();return json({ok:true})}}
if(p==="/api/admin/media"&&m==="POST"){if(!hasPerm(c,"media"))return json({error:"Нет доступа"},403);if(!env.MEDIA)return json({error:"Хранилище изображений не настроено"},503);const ct=request.headers.get("content-type")||"";if(!/^image\/(jpeg|png|webp|avif)$/.test(ct.split(";")[0]))return json({error:"Разрешены JPG, PNG, WEBP, AVIF"},400);const len=Number(request.headers.get("content-length")||0);if(len>12*1024*1024)return json({error:"Файл больше 12 МБ"},413);const u=new URL(request.url),kind=u.searchParams.get("kind")||"route",routeId=Number(u.searchParams.get("route_id")||0);if(kind==="route"&&!routeId)return json({error:"Не указан маршрут"},400);const ext=ct.split("/")[1].replace("jpeg","jpg"),key="images/"+(kind==="home"?"home":"route-"+routeId)+"-"+crypto.randomUUID()+"."+ext;const old=kind==="home"?(await env.DB.prepare("SELECT value FROM app_settings WHERE key='home_image_key'").first())?.value:(await env.DB.prepare("SELECT image_key FROM routes WHERE id=?").bind(routeId).first())?.image_key;await env.MEDIA.put(key,request.body,{httpMetadata:{contentType:ct.split(";")[0],cacheControl:"public, max-age=31536000, immutable"}});if(kind==="home")await env.DB.prepare("INSERT INTO app_settings(key,value) VALUES('home_image_key',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(key).run();else await env.DB.prepare("UPDATE routes SET image_key=? WHERE id=?").bind(key,routeId).run();if(old&&old!==key)await env.MEDIA.delete(old);return json({ok:true,key,url:new URL("/media/"+key,request.url).toString()})}
if(p==="/api/admin/media"&&m==="DELETE"){if(!hasPerm(c,"media"))return json({error:"Нет доступа"},403);if(!env.MEDIA)return json({error:"Хранилище изображений не настроено"},503);const b=await request.json(),kind=String(b.kind||"route"),routeId=Number(b.route_id||0);const key=kind==="home"?(await env.DB.prepare("SELECT value FROM app_settings WHERE key='home_image_key'").first())?.value:(await env.DB.prepare("SELECT image_key FROM routes WHERE id=?").bind(routeId).first())?.image_key;if(key)await env.MEDIA.delete(key);if(kind==="home")await env.DB.prepare("DELETE FROM app_settings WHERE key='home_image_key'").run();else await env.DB.prepare("UPDATE routes SET image_key=NULL WHERE id=?").bind(routeId).run();return json({ok:true})}
if(p.startsWith("/media/")&&m==="GET"){if(!env.MEDIA)return new Response("Not found",{status:404});const key=decodeURIComponent(p.slice(7));if(!/^images\/[A-Za-z0-9._-]+$/.test(key))return new Response("Not found",{status:404});const obj=await env.MEDIA.get(key);if(!obj)return new Response("Not found",{status:404});const headers=new Headers();obj.writeHttpMetadata(headers);headers.set("etag",obj.httpEtag);headers.set("cache-control","public, max-age=31536000, immutable");return new Response(obj.body,{headers})}
return null}
export default {async fetch(request,env){const r=await handle(request,env);return r||env.ASSETS.fetch(request)}};