name = "wild-east-club"
main = "src/index.js"
compatibility_date = "2026-09-18"

[assets]
directory = "../miniapp"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "wild-east-club"
database_id = "2f42f260-35be-4050-af64-36a53fbdc27e"

[vars]
ADMIN_ID = "462776734"
